---
dependency:
  name: galaxy
driver:
  name: vagrant
  provider:
    name: parallels
lint:
  name: yamllint
platforms:
  - name: instance
    box: centos/7
provisioner:
  name: ansible
  inventory:
    host_vars:
      instance:
        ansible_become: true
  lint:
    name: ansible-lint
